- name:  install apache
  apt: pkg=apache2 state=present


- name: apache2 service state
  service: name=apache2 enabled=yes

- name: apache site configuration
  copy:
     src=cw.vhost.debian.conf
     dest=/etc/apache2/sites-available/
     owner=root
     group=root
     mode=0644

- name: enable apache site
  shell: /usr/sbin/a2dissite 000-default && /usr/sbin/a2ensite cw.vhost.debian.conf
  notify: restart apache

