- name: Install http and php etc
  yum: name={{ item }} state=present
  with_items:
   - httpd

- name: httpd site configuration
  copy:
     src=cw.vhost.redhat.conf
     dest=/etc/httpd/conf.d/
     owner=root
     group=root
     mode=0644
  notify: restart httpd
