---
- name: Add NodeSource repositories for Node.js.
  shell: curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -

- name: Ensure build dependencies are installed (Debian).
  apt: 'name="{{ item }}" state=installed'
  with_items:
     - nodejs
