- name: setup glusterfs
  include: setup-Redhat.yml
  when: ansible_os_family == 'RedHat'

- name: setup glusterfs
  include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"

- name: Configure Gluster volume.
  gluster_volume:
     state: present
     name: "{{ gluster_brick_name }}"
     brick: "{{ gluster_brick_dir }}"
     replicas: 2
     cluster: "{{ node.1 }},{{ node.2 }}"
     host: "{{ ansible_eth0.ipv4.address  }}"
     force: yes
  when: ansible_eth0.ipv4.address=="{{ node.1 }}"

- name: Wait until glsuterds is available
  local_action:
    module: wait_for
    host: "{{ node.2 }}"
    port: 24007
    delay: 60
    timeout: 320
    state: started


- name: Start Gluster volume
  gluster_volume: name={{ gluster_brick_name }} state=started
  when: ansible_eth0.ipv4.address=="{{ node.1 }}"
