- name: setup glusterfs
  include: setup-Redhat.yml
  when: ansible_os_family == 'RedHat'

- name: setup glusterfs
  include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"


- name: Configure Gluster volume.
  gluster_volume:
     state: present
     name: "{{ gluster_brick_name }}"
     brick: "{{ gluster_brick_dir }}"
     replicas: 2
     cluster: "{{ node.1 }},{{ node.2 }}"
     host: "{{ ansible_eth0.ipv4.address  }}"
     force: yes
  when: ansible_eth0.ipv4.address=="{{ node.1 }}"

- name : wait apache is up
  action: shell nc -vz {{ node.2 }} 24007
  register: result
  until: result.stdout.find("succeeded") != -1 or result.stdout.find("open") != -1
  retries: 5
  delay: 10
  when: ansible_eth0.ipv4.address=="{{ node.1 }}"


- name: Start Gluster volume
  gluster_volume: name={{ gluster_brick_name }} state=started
  when: ansible_eth0.ipv4.address=="{{ node.1 }}"
