- name: setup glusterfs
  include: setup-Redhat.yml
  when: ansible_os_family == 'RedHat'

- name: setup glusterfs
  include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"

- name : wait gluster 2 is up
  wait_for: host={{ item }} port=24007
  with_items:
    - node.1
    - node.2
  when: ansible_default_ipv4.address=="{{ node.1 }}"


- name: Configure Gluster volume.
  gluster_volume:
     state: present
     name: "{{ gluster_brick_name }}"
     brick: "{{ gluster_brick_dir }}"
     replicas: 2
     cluster: "{{ node.1 }},{{ node.2 }}"
     host: "{{ ansible_default_ipv4.address }}"
     force: yes
  when:  ansible_default_ipv4.address=="{{ node.1 }}"

- name: Start Gluster volume
  gluster_volume: name={{ gluster_brick_name }} state=started
  when: ansible_default_ipv4.address=="{{ node.1 }}"

