- name: setup glusterfs
  include: setup-Redhat.yml
  when: ansible_os_family == 'RedHat'

- name: setup glusterfs
  include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"

- name: Configure Gluster volume.
  gluster_volume:
     state: present
     name: "{{ gluster_brick_name }}"
     brick: "{{ gluster_brick_dir }}"
     replicas: 2
     cluster: "{{ clusters}}"
     host: "{{ ansible_eth0.ipv4.address  }}"
     force: yes
  when: ansible_eth0.ipv4.address=="{{ gluster_master }}"

- name: wait gluster 2 
  wait_for: host=0.0.0.0 port=24007 state=drained exclude_hosts={{ gluster_master }}


- name: Start Gluster volume
  gluster_volume: name={{ gluster_brick_name }} state=started
  when: ansible_eth0.ipv4.address=="{{ gluster_master }}"
