- name: update apt cache
  apt: >
       update_cache=yes

- name: Ensure GlusterFS is installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - glusterfs-server
    - glusterfs-client

- name: glusterfs-service state
  service: name=glusterfs-server enabled=yes

