- name: apt-get update & upgrade
  apt: upgrade=full update_cache=yes
  ignore_errors: yes

- name: install common packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - glusterfs-client
    - nfs-common
    - git
    - rsync


