- name: packages installed Debian 8 and Ubuntu trusty
  apt: pkg={{ item }} state=present
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mysql
    - php5-xmlrpc
    - php5-gd
    - php5-mcrypt
    - php5-json
    - php5-curl
    - php5-redis


- name: packages installed Ubuntu xenial
  apt: pkg={{ item }} state=present
  with_items:
    - php
    - libapache2-mod-php
    - php-mysql
    - php-curl
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-xml
    - php-xmlrpc
    - php-json
    - php-curl
    - php-redis