clusters: 10.0.1.2,10.0.1.3
ip_node: 10.0.1.2
hostname: node1
master: true

db_name: test
db_admin: admin
db_admin_password: changeme

#on pv_disk you can use many disks juste add , exemple /dev/vdb , /dev/vdc
pv_disk: /dev/vdb
vg_name: vg0
lv_name: global
lv_size : 8g
